version: '3.1'

services:
  postgres:
    container_name: oryapp-postgres
    image: postgis/postgis:13-3.2
    restart: always
    environment:
      POSTGRES_USER: oryapp
      POSTGRES_PASSWORD: oryapp
      POSTGRES_DB: oryapp
    ports:
      - 5432:5432

  adminer:
    image: dockette/adminer:full
    restart: always
    ports:
      - 8080:80
